config/routes.rb
Rails.application.routes.draw do
  # Devise routing
  devise_for :user, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_scope :user do
    post 'register' => 'registrations#create'
  end

  authenticated :user do
    root 'websites#index', as: :authenticated_root
  end

  # Root path
  root 'pages#home'
  get "/faq" => "pages#faq", as: "faq"
  resources :websites
  resources :contacts, only: [:new, :create]

  # Scrapers routing
  get 'get-home-articles' => 'scrapers#get_home_articles', as: 'get_home_articles'
  get 'home-scan' => 'scrapers#home_scan', as: 'home_scan'

  get "get-articles" => 'scrapers#get_articles', as: "get_articles"
  get "close-stream" => "scrapers#close_stream", as: "close_stream"
end

app/models/website.rb
# frozen_string_literal: true
class Website < ApplicationRecord
  require 'open-uri'

  has_and_belongs_to_many :users
  has_many :articles, dependent: :destroy

  before_save do
    uri = URI.parse(link)
    uri = URI.parse("http://#{link}") if uri.scheme.nil?
    host = uri.host.downcase
    self.link = host.start_with?('www.') ? host[4..-1] : host
  end

  validates :link, uniqueness: true

  # --------------------- MODEL METHODS ----------------------
  def to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << Article.column_names
      self.articles.each do |article|
        csv << article.attributes.values_at(*Article.column_names)
      end
    end
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_filter :logged_in_user?

  def index
    @websites = current_user.websites
  end

  def show
    @website = Website.find(params[:id])
    @articles = @website.articles.limit(500).order("crawled DESC").order("total_shares DESC")
    respond_to do |format|
      format.html
      format.xls do
        headers["Content-Disposition"] = "attachment; filename=\"#{@website.link}\""
        send_data @website.to_csv(col_sep: "\t")
      end
    end
  end

  def new

  end

  def destroy
    current_user.websites.delete(params[:id].to_i)
    redirect_to websites_path
  end
end

app/views/websites/index.html.erb
<%= render "shared/header_dark" %>
<div class="topmargin fancy-title title-center" style="position: static;">
  <h1>My Saved Websites
    <%= link_to "+ Add New", new_website_path, class:"button button-circle button-small", style: "vertical-align: middle;"  %></h1>
</div>
<div class="col-md-8 col-md-offset-2">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Website</th>
        <th># Articles</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @websites.each_with_index do |website, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td><%= link_to website.link, website_path(website) %></td>
          <td><%= website.articles.size %></td>
          <td><%= website.status? ? "Complete" : "Incomplete" %></td>
          <td>
            <%= link_to website_path(website), class: "button button-mini button-circle button-blue" do %>
            <i class="icon-search"></i>View
            <% end %> |
            <%= link_to website_path(website), method: :delete, data: {confirm: "Are you sure you want to remove this website from your list?"}, class: "button button-mini button-circle button-red" do %>
            <i class="icon-trash"></i>Delete
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/websites/new.html.erb
<%= render "shared/header_dark" %>
<div class="col-md-8 col-md-offset-2">
  <div class="fancy-title topmargin title-center">
    <h1>Crawl New Website</h1>
  </div>
  <%= form_for :scrape_job, url: get_articles_path, method: "get",  html: {id: "scrape-form", class: "clearfix", style:"z-index: 9999;"} do |f| %>
    <div class="col_two_third nobottommargi">
      <%= f.text_field :url, class: "form-control input-lg not-dark", placeholder: "http://mycoolwebsite.com/" %>
    </div>
    <div class="col_one_third col_last nobottommargin">
      <%= f.submit "Search", class: "btn btn-lg btn-danger btn-block nomargin" %>
    </div>
  <% end %>
</div>
<div class="col-md-10 col-md-offset-1">
  <div id="section-features" class="heading-block title-center page-section">
    <h2>Type In A Url To Start Searching</h2>
    <%= link_to close_stream_path, id: "update-button-new",class:"button button-red button-circle button-small", style: "display:none; vertical-align: middle;"  do %>
      <i class="icon-stop"></i>  Stop
  <% end %>
    <span class="amount"></span>
  </div>
  <div class="table-responsive">
    <div id="datatable1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
      <div class="row">
        <div class="col-sm-12">
          <table id="datatable1" class="table table-striped table-bordered dataTable" cellspacing="0" width="100%">
            <thead>
              <tr role="row">
                <th>#</th>
                <th>URL</th>
                <th>Total Shares</th>
                <th>Facebook Shares</th>
                <th>Twitter Shares</th>
                <th>LinkedIn Shares</th>
                <th>Pinterest Pins</th>
                <th>Google +'es</th>
                <th>Comments</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>#</th>
                <th>URL</th>
                <th>Total Shares</th>
                <th>Facebook Shares</th>
                <th>Twitter Shares</th>
                <th>LinkedIn Shares</th>
                <th>Pinterest Pins</th>
                <th>Google +'es</th>
                <th>Comments</th>
              </tr>
            </tfoot>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<% content_for :js do %>
  <%= javascript_include_tag "website_scraper" %>
  <script>
    $("#datatable1").DataTable({
              "iDisplayLength": 50,
              "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]]
            });
  </script>
<% end %>

app/views/websites/show.html.erb
<%= render "shared/header_dark" %>
<div class="col-md-10 col-md-offset-1">
  <div class="topmargin margin-bottom fancy-title title-center" style="position: static;">
    <h1>Shares & Comments For <span><%= @website.link.capitalize %></span>
      <%= link_to get_articles_path(scrape_job: {url: @website.link}), data: {url: @website.link}, id: "update-button", class:"button button-circle button-small", style: "vertical-align: middle;"  do %>
        <i class="icon-refresh"></i>  Update
    <% end %>
    <%= link_to close_stream_path, id: "update-button", class:"button button-red button-circle button-small", style: "vertical-align: middle;"  do %>
      <i class="icon-stop"></i>  Stop
  <% end %>
    </h1>
    <p>Last Updated at <span style="font-weight:bold;"><%= @website.last_crawled.strftime("%B %d, %Y") %></span>
      <%= link_to website_path(site: @website.link, format: :xls), class:"button button-circle button-mini button-red", style: "vertical-align: middle;"  do %>
        <i class="icon-download"></i>  Download Excel
    <% end %>
    </p>
  </h1>
</div>
<div class="table-responsive">
  <div id="datatable1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
    <div class="row">
      <div class="col-sm-12">
        <table id="datatable1" class="table table-striped table-bordered dataTable" cellspacing="0" width="100%" data-articles='<%= raw @articles.to_json %>'>
          <thead>
            <tr role="row">
              <th>#</th>
              <th>URL</th>
              <th>Total Shares</th>
              <th>Facebook Shares</th>
              <th>Twitter Shares</th>
              <th>LinkedIn Shares</th>
              <th>Pinterest Pins</th>
              <th>Google +'es</th>
              <th>Comments</th>
            </tr>
          </thead>
          <tfoot>
          </tfoot>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>
<% content_for :js do %>
  <script>
    var table = $("#datatable1").DataTable({
              "iDisplayLength": 50,
              "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]]
            });
            arr = $("#datatable1").data("articles")
            for (var i = 0; i < arr.length; i++) {
              table.row.add([
                  i + 1,
                  "<a target='_blank' href='" + arr[i].link + "'>" + arr[i].link + "</a>",
                  arr[i].total_shares,
                  arr[i].facebook_shares,
                  arr[i].twitter_shares,
                  arr[i].linkedin_shares,
                  arr[i].pinterest_pins,
                  arr[i].google_shares,
                  arr[i].comments
              ]).draw(true);
            }
  </script>
  <%= javascript_include_tag "update" %>
<% end %>