config/routes.rb
Rails.application.routes.draw do
  # Devise routing
  devise_for :user, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_scope :user do
    post 'register' => 'registrations#create'
  end

  authenticated :user do
    root 'websites#index', as: :authenticated_root
  end

  # Root path
  root 'pages#home'
  get "/faq" => "pages#faq", as: "faq"
  resources :websites
  resources :contacts, only: [:new, :create]

  # Scrapers routing
  get 'get-home-articles' => 'scrapers#get_home_articles', as: 'get_home_articles'
  get 'home-scan' => 'scrapers#home_scan', as: 'home_scan'

  get "get-articles" => 'scrapers#get_articles', as: "get_articles"
  get "close-stream" => "scrapers#close_stream", as: "close_stream"
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %><div id="error_explanation"> <div class="alert alert-danger"> The form contains <%=pluralize(object.errors.count, "error")%> </div><ul> <% object.errors.full_messages.each do |msg| %> <li><%=msg %></li><% end %> </ul></div><% end %>

app/views/shared/_header.html.erb
<header id="header" class="transparent-header page-section dark">
  <div id="header-wrap">
    <div class="container clearfix">
      <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>
      <nav id="primary-menu">
        <ul class="one-page-menu">
          <li class="current">
            <%= link_to root_path, class: "header-link" do %>
              <div>Home</div>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: "header-link" do %>
                <div>Logout</div>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_session_path, class: "header-link" do %>
                <div>Login</div>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: "header-link" do %>
                <div>Register</div>
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to faq_path, class: "header-link" do %>
              <div>FAQ</div>
            <% end %>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/shared/_header_dark.html.erb
<header id="header" class="transparent-header page-section dark sticky-header">
  <div id="header-wrap">
    <div class="container clearfix">
      <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>
      <!-- #logo end -->
      <nav id="primary-menu">
        <ul class="one-page-menu sf-js-enabled" style="touch-action: pan-y;">
          <li class="current">
            <%= link_to root_path do %>
              <div><%= user_signed_in? ? "Dashboard" : "Home" %></div>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <div>Logout</div>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_session_path do %>
                <div>Login</div>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <div>Register</div>
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to faq_path do %>
              <div>FAQ</div>
            <% end %>
          </li>
        </ul>
      </nav><!-- #primary-menu end -->
    </div>
  </div>
</header>
</div>
<% content_for :js do %>
  <%= javascript_include_tag "jquery_ujs" %>
<% end %>