config/routes.rb
Rails.application.routes.draw do
  # Devise routing
  devise_for :user, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  devise_scope :user do
    post 'register' => 'registrations#create'
  end

  authenticated :user do
    root 'websites#index', as: :authenticated_root
  end

  # Root path
  root 'pages#home'
  get "/faq" => "pages#faq", as: "faq"
  resources :websites
  resources :contacts, only: [:new, :create]

  # Scrapers routing
  get 'get-home-articles' => 'scrapers#get_home_articles', as: 'get_home_articles'
  get 'home-scan' => 'scrapers#home_scan', as: 'home_scan'

  get "get-articles" => 'scrapers#get_articles', as: "get_articles"
  get "close-stream" => "scrapers#close_stream", as: "close_stream"
end

app/views/pages/faq.html.erb
<div id="wrapper" class="clearfix">
  <%= render "shared/header_dark" %>
  <section class="topmargin">
    <div class="container clearfix">
      <div id="section-specs" class="heading-block title-center page-section">
        <h2>FAQ</h2>
        <span>List of frequently asked questions</span>
      </div>
      <div id="side-navigation" class="ui-tabs ui-widget ui-widget-content ui-corner-all">
        <div class="col_one_third">
          <ul class="sidenav ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all" role="tablist">
            <li class="ui-state-default ui-corner-top ui-tabs-active ui-state-active" role="tab" tabindex="0" aria-controls="snav-content1" aria-labelledby="ui-id-1" aria-selected="true" aria-expanded="true"><a href="#snav-content1" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-1"><i class="icon-magic"></i>How does the application work?<i class="icon-chevron-right"></i></a></li>
            <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="snav-content2" aria-labelledby="ui-id-2" aria-selected="false" aria-expanded="false"><a href="#snav-content2" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-2"><i class="icon-stop"></i>I've hit a rate limit, what do I do?<i class="icon-chevron-right"></i></a></li>
            <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="snav-content3" aria-labelledby="ui-id-3" aria-selected="false" aria-expanded="false"><a href="#snav-content3" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-3"><i class="icon-question"></i>I have a feature request/found a bug, what do I do?<i class="icon-chevron-right"></i></a></li>
            <li class="ui-state-default ui-corner-top" role="tab" tabindex="-1" aria-controls="snav-content4" aria-labelledby="ui-id-4" aria-selected="false" aria-expanded="false"><a href="#snav-content4" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-4"><i class="icon-frown"></i>Why are there so few pictures of baby ostriches on this website?<i class="icon-chevron-right"></i></a></li>
          </ul>
        </div>
        <div class="col_two_third col_last">
          <div id="snav-content1" aria-labelledby="ui-id-1" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-hidden="false" style="display: block;">
            <h3>Explainer Video</h3>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/Z1w5bXbUS5w" frameborder="0" allowfullscreen></iframe>
  							</div>
          <div id="snav-content2" aria-labelledby="ui-id-2" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-hidden="true" style="display: none;">
            <h3>Rate limits</h3>
            Facebook and Google have a rate limit of the # of times I can retrieve the shares for a certain website, therefore I can't retrieve all the articles at once. Try again in 1 hour (that's the cooldown time). I've found ways to bypass this, but that would cost money to set up and therefore I haven't fully implemented it yet. Depending on the popularity of the application I might expand it.
  							</div>
          <div id="snav-content3" aria-labelledby="ui-id-3" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-hidden="true" style="display: none;">
            <h3>Feature Requests</h3>
            Send me an email to info[at]truetech.be or use the feedback form in the lower left corner. If you're having a bug, maybe include a video to show it so it's easier to solve!
  							</div>
          <div id="snav-content4" aria-labelledby="ui-id-4" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-hidden="true" style="display: none;">
            <h3>Baby Ostriches</h3>
            <%= image_tag "ostrich" %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <% content_for :js do %>
    <script type="text/javascript">
      $(function() {
                    $( "#side-navigation" ).tabs({ show: { effect: "fade", duration: 400 } });
                  });
    </script>
  <% end %>

app/views/pages/home.html.erb
<div id="wrapper" class="clearfix">
  <%= render "shared/header" %>
  <section id="slider" class="slider-parallax dark full-screen" style="background-image: url(<%= asset_path("book") %>); background-size: cover;">
    <div class="container clearfix">
      <div class="vertical-middle">
        <div class="heading-block center nobottomborder">
          <h1 class="topmargin" data-animate="fadeInUp">Find the most popular articles for ANY website
          </h1>
          <a href="/faq#snav-content1" style="vertical-align: middle;" data-animate="fadeInUp" class="button button-3d button-small button-amber"><i class="icon-play" aria-hidden="true"></i> Explainer Video</a>
        </div>
        <%= form_for :scrape_job, url: get_home_articles_path, method: "get",  html: {id: "scrape-form-home", class: "landing-wide-form clearfix"} do |f| %>
          <div class="col_two_third nobottommargin">
            <%= f.text_field :url, class: "form-control input-lg not-dark", placeholder: "http://mycoolwebsite.com/" %>
          </div>
          <div class="col_one_third col_last nobottommargin">
            <%= f.submit "Search", class: "btn btn-lg btn-danger btn-block nomargin" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</section>
<section id="content">
  <div class="content-wrap">
    <div class="container clearfix">
      <div id="section-features" class="heading-block title-center page-section">
        <h2>Type In A Url To Start Searching</h2>
        <span class="amount"></span>
        <%= link_to home_scan_path, class: "scrape-button button button-3d button-rounded button-amber hidden" do %>
          <i class="icon-search"></i>Scan Articles!
          <% end %>
      </div>
      <div class="table-responsive">
        <div id="datatable1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
          <div class="row">
            <div class="col-sm-12">
              <table id="datatable1" class="table table-striped table-bordered dataTable" cellspacing="0" width="100%">
                <thead>
                  <tr role="row">
                    <th>#</th>
                    <th>URL</th>
                    <th>Total Shares</th>
                    <th>Facebook Shares</th>
                    <th>Twitter Shares</th>
                    <th>LinkedIn Shares</th>
                    <th>Pinterest Pins</th>
                    <th>Google +'es</th>
                    <th>Comments</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>#</th>
                    <th>URL</th>
                    <th>Total Shares</th>
                    <th>Facebook Shares</th>
                    <th>Twitter Shares</th>
                    <th>LinkedIn Shares</th>
                    <th>Pinterest Pins</th>
                    <th>Google +'es</th>
                    <th>Comments</th>
                  </tr>
                </tfoot>
                <tbody>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="mpf-content modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-body">
      <div class="modal-content">
        <div class="modal-body">
          <div class="block divcenter">
            <div style="padding: 20px;">
              <div class="heading-block nobottomborder bottommargin-sm" style="max-width:500px;">
                <h4>Get all the articles, shares & comments for <span class="url"></span></h4>
                <span>To get more data for this site, you'll have to create an account!</span>
              </div>
              <div class="widget-subscribe-form-result"></div>
              <%= form_for(@user, url: new_user_registration_path, html: {class: "widget-subscribe-form2", style:"max-width: 350px; margin: 0 auto;"}) do |f| %>
                <%= devise_error_messages! %>
                <%= f.email_field :email, autofocus: true, class: "form-control input-lg not-dark required email", style:"margin-bottom:10px;", placeholder:"Enter your Email" %>
                <%= f.password_field :password, class: "form-control input-lg not-dark required email", style:"margin-bottom:10px;", placeholder:"Enter a password" %>
                <%= f.password_field :password_confirmation, class: "form-control input-lg not-dark required email", style:"margin-bottom:10px;", placeholder:"Enter your password again" %>
                <%= hidden_field_tag :url, id: "url-field" %>
                <%= f.submit "Gimme!", class: "button button-rounded button-border button-dark noleftmargin",  style:"margin-top:15px;" %>
                <p class="nobottommargin" style="margin-top: 15px;"><small><em>*We hate Spam &amp; Junk Emails too. It's just for identification, no newsletters. email confirmation is required.</em></small></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% content_for :js do %>
  <script>
    $(document).ready(function() {
      $('#datatable1').DataTable({
        "iDisplayLength": 50,
        "aLengthMenu": [[25, 50, 100, -1], [25, 50, 100, "All"]]
      });
    });
  </script>
  <%= javascript_include_tag "homepage" %>
<% end %>